import { BadRequestException,NotFoundException } from '@nestjs/common'; import { RequestsService } from './requests.service';
const body={pastaJuridicaId:'11111111-1111-4111-8111-111111111111',processoId:'22222222-2222-4222-8222-222222222222',descricao:'Danos morais',categoria:'Indenização',situacao:'EM_ANDAMENTO',estimativaExito:75,valorPedidoCentavos:'10000'};
describe('RequestsService',()=>{function setup(folder:any={id:body.pastaJuridicaId},link:any={processoId:body.processoId}){const item={id:'pedido-1',...body,escritorioId:'office-a',estimativaExito:{toString:()=> '75'},valorPedidoCentavos:10000n,valorProvavelCentavos:null,valorPossivelCentavos:null,valorRemotoCentavos:null,valorFinalCentavos:null,pastaJuridica:{id:body.pastaJuridicaId,nome:'PASTA/1',clientePrincipal:{id:'c1',nome:'Cliente'}},processo:null};const client={pastaJuridica:{findFirst:jest.fn().mockResolvedValue(folder)},pastaJuridicaProcesso:{findFirst:jest.fn().mockResolvedValue(link)},pedido:{create:jest.fn().mockResolvedValue(item),findFirst:jest.fn().mockResolvedValue(item),update:jest.fn().mockResolvedValue(item),findMany:jest.fn().mockResolvedValue([item]),count:jest.fn().mockResolvedValue(1)},$transaction:jest.fn().mockResolvedValue([[item],1])};return {client,service:new RequestsService({client} as never)}}
it('cria somente com Pasta tenant-scoped e Processo da mesma Pasta',async()=>{const {service,client}=setup();await service.create('office-a',body);expect(client.pastaJuridica.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({escritorioId:'office-a'})}));expect(client.pastaJuridicaProcesso.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({pastaJuridicaId:body.pastaJuridicaId,processoId:body.processoId})}));});
it('rejeita Pasta inexistente ou cross-tenant',async()=>{const {service}=setup(null);await expect(service.create('office-a',body)).rejects.toBeInstanceOf(NotFoundException)});
it('rejeita Processo que não pertence à Pasta',async()=>{const {service}=setup({id:body.pastaJuridicaId},null);await expect(service.create('office-a',body)).rejects.toBeInstanceOf(BadRequestException)});
it('serializa BigInt financeiro sem perda',async()=>{const {service}=setup();await expect(service.get('office-a','pedido-1')).resolves.toEqual(expect.objectContaining({valorPedidoCentavos:'10000',estimativaExito:'75'}))});
it('lista com total e paginação server-side',async()=>{const {service}=setup();const result=await service.list('office-a',{sort:'-criadoEm',page:1,limit:20} as never);expect(result.total).toBe(1);expect(result.items).toHaveLength(1)});
it('remove por soft delete',async()=>{const {service,client}=setup();await service.remove('office-a','pedido-1');expect(client.pedido.update).toHaveBeenCalledWith({where:{id:'pedido-1'},data:{excluidoEm:expect.any(Date)}})});});
